// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIjcUXCHXbbT2Pn5ixzMJ5dCwmmtCaaUI',
    appId: '1:692788093576:android:b21edd49a22b4d2a45753d',
    messagingSenderId: '692788093576',
    projectId: 'movibus-uptp',
    storageBucket: 'movibus-uptp.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6BafVm_KXl6L5PYnJmYh6bysqM0c3S1o',
    appId: '1:692788093576:ios:dd23f77a99e21dc345753d',
    messagingSenderId: '692788093576',
    projectId: 'movibus-uptp',
    storageBucket: 'movibus-uptp.firebasestorage.app',
    iosBundleId: 'com.uptp.moove',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAb3UXXzed-zaQywYoDKpufEpfJBKA2Boo',
    appId: '1:692788093576:web:ba6e8f4c022a31e845753d',
    messagingSenderId: '692788093576',
    projectId: 'movibus-uptp',
    authDomain: 'movibus-uptp.firebaseapp.com',
    storageBucket: 'movibus-uptp.firebasestorage.app',
  );
}
